version: '3.8'

services:
  golf-course-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golf-course-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      # Mount source code for development (optional - remove for production)
      - ./app:/app/app:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - golf-course-network

networks:
  golf-course-network:
    driver: bridge
