version: '3.8'

services:
  golf-tracker-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ENVIRONMENT=development
      - API_HOST=0.0.0.0
      - API_PORT=8000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - golf-tracker-network

networks:
  golf-tracker-network:
    driver: bridge
