apiVersion: v1
kind: Namespace
metadata:
  name: golftracker
  labels:
    name: golftracker
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: golftracker-dev
  labels:
    name: golftracker-dev
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: monitoring
